<!DOCTYPE html>
<html lang="ru">
    <head>
        <meta charset="UTF-8">
        <title>Profile</title>
        <link href = "../user-profile-tpl/styles/style.css" rel = "stylesheet"/>
    </head>
    <body>
        <div class = "sidebar">
            <input type = "image" name = "home-button" class = "home-button" src = "../../static/Home 24.png" alt = "Try Ctrl-R"/>
            <div class = "profile-button-container">
                <input type = "image" name = "profile-button" class = "profile-button" src = "../../static/User 24.png" alt = "Try Ctrl-R"/>
                <div class = "active-window-symbol"></div>
            </div>
            <input type = "image" name = "plus-button" class = "plus-button" src = "../../static/Plus 24.png" alt = "Try Ctrl-R"/>
        </div>
        <div class = "main-content">
            <div class = "header">
                <img src = "<?=$user_avatar?>" alt = "Try Ctrl-R" class = "user-avatar"/>
                <span class = "user-name"><?=$user_name?></span>
                <span class = "user-status"><?=$user_status?></span>
                <div class = "posts-count-container">
                    <img src = "../../static/Image 16.png" alt = "Try Ctrl-R" class = "post-icon">
                    <span class = "posts-count"><?=$posts_count . " " . $posts_count_describe?></span>
                </div>
            </div>
            <div class = "posts-container">
                <?=$posts_preview_links_list?>
            </div>
        </div>
    </body>
</html>